version: '3'
services:
  app:
    build: .
    environment:
      ALLOW_ORIGINS: "http://localhost:8080"
      DEBUG: "true"
      SWAGGER_HOST: 127.0.0.1

  secret:
    environment:
      - "DEVELOPMENT=true"
    volumes:
      - /tmp/secret:/tmp/secret

  db:
    ports:
      - "8306:3306"